CREATE TABLE USER (
        ID BIGINT NOT NULL AUTO_INCREMENT,
        USER_NM VARCHAR(50) NOT NULL,
        PASSWD VARCHAR(50) NOT NULL,
        NM VARCHAR(50) NOT NULL,
        PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO USER (USER_NM, PASSWD, NM) VALUES ('admin', 'admin', 'Administrator');
